### ISSUE TITLE
Where can I find the settings for user/pass [elastic/changeme] 

### ISSUE THREAD

**Issue by Simonchik** [thirtybees/elasticsearch#34]
I use docker-compose to run the TB, but can't find where in the module I can setup the user/pass [default values are: elastic/changeme]. I only see the server's url.

```
version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/default
      - ./docker_images/config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - thirtybees-network

  php:
    build: ./docker_images/php7-fpm
    volumes:
      - ./www:/var/www/default
    networks:
      - thirtybees-network

  mysql:
    image: mariadb
    environment:
      - MYSQL_DATABASE=thirtybees
      - MYSQL_USER=thirtybees
      - MYSQL_PASSWORD=thirtybees
      - MYSQL_ROOT_PASSWORD=root

    networks:
      - thirtybees-network

  memcached:
    image: memcached:latest
    networks:
      - thirtybees-network

  elasticsearch1:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
      container_name: elasticsearch1
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
      volumes:
        - ./esdata1:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      networks:
        - thirtybees-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 88:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - thirtybees-network

networks:
  thirtybees-network:
    driver: bridge
```
